# Variables just for the development environment. These will override the variables in _config.yml when running jekyll serve --config _config.yml,_config.dev.yml
title                    : "Bible By Example (Dev)"
url                      : "https://dev.biblebyexample.com"
environment              : development

breadcrumbs              : true # true, false (default)

# Sass/SCSS
sass:
  style                  : expanded # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Disable the style guide/style check pages in dev
collections:
  styleguide:
    output               : true
